# Generated by Django 3.1.7 on 2021-12-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('when', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('On-Going Events', 'On-Going Events'), ('Upcoming Events', 'Upcoming Events'), ('Completed Events', 'Completed Events')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Job Post', 'Job Post'), ('Partner Company', 'Partner Company'), ('job seekers', 'job seekers')], max_length=200, null=True)),
            ],
        ),
    ]
