# Generated by Django 3.1.7 on 2022-01-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0002_event_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('Gender', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='JoinEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alumniname', models.CharField(max_length=200, null=True)),
                ('Eventname', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
