# Generated by Django 3.1.7 on 2022-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0003_alumni_joinevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinevent',
            old_name='Alumniname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='joinevent',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='joinevent',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
