# Generated by Django 3.1.7 on 2022-01-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0004_auto_20220107_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinevent',
            name='Eventname',
        ),
        migrations.AddField(
            model_name='joinevent',
            name='eventname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CITAT.event'),
        ),
    ]
