# Generated by Django 3.1.7 on 2022-01-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0005_auto_20220107_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinevent',
            name='alumni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CITAT.alumni'),
        ),
    ]
