# Generated by Django 3.1.7 on 2022-01-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0006_joinevent_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinevent',
            name='firstname',
        ),
    ]
