# Generated by Django 3.1.7 on 2022-01-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0008_auto_20220107_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinevent',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
