# Generated by Django 3.1.7 on 2022-01-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0009_joinevent_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='when',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
