# Generated by Django 3.1.7 on 2022-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0010_auto_20220121_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_yes', models.BooleanField(default=False, verbose_name='Yes')),
                ('employed_no', models.BooleanField(default=False, verbose_name='No')),
                ('income', models.CharField(max_length=200, null=True)),
                ('skill_yes', models.BooleanField(default=False, verbose_name='Yes')),
                ('skill_no', models.BooleanField(default=False, verbose_name='No')),
            ],
        ),
        migrations.CreateModel(
            name='UserSelfemployed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_yes', models.BooleanField(default=False, verbose_name='Yes')),
                ('related_no', models.BooleanField(default=False, verbose_name='No')),
                ('numberofemployee', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUnemployed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_yes', models.BooleanField(default=False, verbose_name='Yes')),
                ('job_no', models.BooleanField(default=False, verbose_name='NO')),
                ('aftergrad', models.CharField(max_length=200, null=True)),
                ('desire_yes', models.BooleanField(default=False, verbose_name='Yes')),
                ('desire_no', models.BooleanField(default=False, verbose_name='No')),
                ('consider_yes', models.BooleanField(default=False, verbose_name='Yes')),
                ('consider_no', models.BooleanField(default=False, verbose_name='No')),
            ],
        ),
    ]
