# Generated by Django 3.1.7 on 2022-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0011_useremployed_userselfemployed_userunemployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployed',
            name='organization',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Government Organization (GO)', 'Government Organization (GO)'), ('Business Organization (BO)', 'Business Organization (BO)'), ('Private Organization', 'Private Organization'), ('Cooperative', 'Cooperative'), ('Non Government Organization', 'Non Government Organization'), ('Peoples Organization', 'Peoples Organization')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useremployed',
            name='selections',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Selection', 'Selection'), ('Retention', 'Retention'), ('Promotion', 'Promotion')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userselfemployed',
            name='business',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Direct Selling', 'Direct Selling'), ('Farming', 'Farming'), ('Fishing', 'Fishing'), ('Franchise', 'Franchise'), ('Franchising', 'Franchising'), ('Service Operation', 'Service Operation'), ('Trading', 'Trading'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userselfemployed',
            name='reason',
            field=models.CharField(choices=[('Higher Income', 'Higher Income'), ('More Flexible Time', 'More Flexible Time'), ('Family Affair', 'Family Affair'), ('Had the opportunity to put up my business', 'Had the opportunity to put up my business'), ('Advised by husband/wife/relatives', 'Advised by husband/wife/relatives'), ('To have time to attend household chores', 'To have time to attend household chores'), ('I want to be the boss of my own', 'I want to be the boss of my own'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userunemployed',
            name='finance',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Supported by parents', 'Supported by parents'), ('Supported by relatives/brothers/sisters', 'Supported by relatives/brothers/sisters'), ('Do buy and sell', 'Do buy and sell'), ('Supported by husband/wife', 'Supported by husband/wife'), ('Farm laborer of other farms', 'Farm laborer of other farms'), ('Entered as domestic helper', 'Entered as domestic helper'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userunemployed',
            name='reasons',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('I cannot find a good job', 'I cannot find a good job'), ('advance or further study first', 'advance or further study first'), ('i do not like to be tied with a job and have a boss', 'i do not like to be tied with a job and have a boss'), ('Advise of husband/wife or relatives', 'Advise of husband/wife or relatives'), ('No job opportunity', 'No job opportunity'), ('Health-related reasons', 'Health-related reasons'), ('Family concern and decided no to find a job', 'Family concern and decided no to find a job'), ('I want to put my own business', 'I want to put my own business'), ('I want to be of my own', 'I want to be of my own'), ('Lack of work experience', 'Lack of work experience'), ('Did not look for job', 'Did not look for job'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
