# Generated by Django 3.1.7 on 2022-03-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0017_alumni_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
