# Generated by Django 3.1.7 on 2022-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0019_auto_20220304_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='Course',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
