# Generated by Django 4.0.2 on 2022-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0022_alter_alumni_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployed',
            name='employed_no',
        ),
        migrations.RemoveField(
            model_name='useremployed',
            name='employed_yes',
        ),
        migrations.AddField(
            model_name='useremployed',
            name='employed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=200, null=True),
        ),
    ]
