# Generated by Django 4.0.2 on 2022-03-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0023_remove_useremployed_employed_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployed',
            name='skill_no',
        ),
        migrations.RemoveField(
            model_name='useremployed',
            name='skill_yes',
        ),
        migrations.AddField(
            model_name='useremployed',
            name='skills',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
