# Generated by Django 4.0.2 on 2022-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0024_remove_useremployed_skill_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userunemployed',
            name='consider_no',
        ),
        migrations.RemoveField(
            model_name='userunemployed',
            name='consider_yes',
        ),
        migrations.RemoveField(
            model_name='userunemployed',
            name='desire_no',
        ),
        migrations.RemoveField(
            model_name='userunemployed',
            name='desire_yes',
        ),
        migrations.RemoveField(
            model_name='userunemployed',
            name='job_no',
        ),
        migrations.RemoveField(
            model_name='userunemployed',
            name='job_yes',
        ),
        migrations.AddField(
            model_name='userunemployed',
            name='consider',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userunemployed',
            name='desire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userunemployed',
            name='seek',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
