# Generated by Django 3.1.7 on 2022-03-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0029_auto_20220311_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployed',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='userselfemployed',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='userunemployed',
            name='alumni',
        ),
    ]
