# Generated by Django 3.1.7 on 2022-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0032_auto_20220311_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployed',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='userselfemployed',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='userunemployed',
            name='alumni',
        ),
        migrations.AlterField(
            model_name='useremployed',
            name='employed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
