# Generated by Django 3.1.7 on 2022-03-11 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CITAT', '0034_useremployed_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployed',
            name='alumni',
        ),
        migrations.AddField(
            model_name='useremployed',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
