# Generated by Django 3.2.7 on 2022-03-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0037_alter_alumni_id_alter_contact_id_alter_event_id_and_more'),
        ('CITAT', '0037_auto_20220311_1814'),
    ]

    operations = [
    ]
