# Generated by Django 3.1.7 on 2022-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0038_auto_20220315_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='Course',
        ),
        migrations.AddField(
            model_name='alumni',
            name='employed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
