# Generated by Django 3.1.7 on 2022-03-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0039_auto_20220315_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='employed',
        ),
    ]
