# Generated by Django 3.1.7 on 2022-03-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0040_remove_alumni_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Course',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
