# Generated by Django 3.1.7 on 2022-03-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0041_alumni_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='employed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
