# Generated by Django 3.1.7 on 2022-03-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0045_auto_20220315_1922'),
        ('CITAT', '0038_merge_20220311_2049'),
    ]

    operations = [
    ]
