# Generated by Django 3.1.7 on 2022-03-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0047_auto_20220316_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployed',
            name='alumni',
        ),
    ]
