# Generated by Django 3.1.7 on 2022-03-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0048_remove_useremployed_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployed',
            name='alumni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CITAT.alumni'),
        ),
    ]
