# Generated by Django 3.1.7 on 2022-03-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0049_useremployed_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployed',
            name='user',
        ),
    ]
