# Generated by Django 3.1.7 on 2022-03-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0050_remove_useremployed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('organization', models.CharField(choices=[('--Select--', '--Select--'), ('Government Organization (GO)', 'Government Organization (GO)'), ('Business Organization (BO)', 'Business Organization (BO)'), ('Private Organization', 'Private Organization'), ('Cooperative', 'Cooperative'), ('Non Government Organization', 'Non Government Organization'), ('Peoples Organization', 'Peoples Organization')], max_length=200, null=True)),
                ('income', models.CharField(choices=[('10,000 - 20,000', '10,000 - 20,000'), ('20,000 - 30,000', '20,000 - 30,000'), ('30,000 - 40,000', '30,000 - 40,000'), ('40,000 - 50,000', '40,000 - 50,000')], max_length=200, null=True)),
            ],
        ),
    ]
