# Generated by Django 3.1.7 on 2022-03-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0051_employed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employed',
            old_name='employed',
            new_name='are_you_employed',
        ),
    ]
