# Generated by Django 3.1.7 on 2022-03-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0052_auto_20220316_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='employed',
            new_name='alumni_employed',
        ),
    ]
