# Generated by Django 3.2.5 on 2022-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0055_auto_20220320_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployedModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=200, null=True)),
                ('Position', models.CharField(max_length=200, null=True)),
                ('Income', models.CharField(max_length=200, null=True)),
                ('Organization', models.CharField(max_length=200, null=True)),
                ('Years_of_experience', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
