# Generated by Django 3.2.5 on 2022-03-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0056_employedmodal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployedModal',
        ),
        migrations.AddField(
            model_name='alumni',
            name='Company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Company_contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Company_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Company_zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Income',
            field=models.CharField(choices=[('10,000-25,000', '10,000-25,000'), ('30,000-40,000', '30,000-40,000'), ('50,000-70,000', '50,000-70,000'), ('More than the choices', 'More than the choices')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Years_of_experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='alumni_employed',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-employed', 'Self-employed')], max_length=200, null=True),
        ),
    ]
