# Generated by Django 3.2.5 on 2022-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0057_auto_20220321_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='Company_address',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Company_contact',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Company_email',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Company_zipcode',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Income',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Years_of_experience',
        ),
        migrations.RemoveField(
            model_name='employed',
            name='are_you_employed',
        ),
        migrations.RemoveField(
            model_name='employed',
            name='income',
        ),
        migrations.RemoveField(
            model_name='employed',
            name='organization',
        ),
        migrations.AddField(
            model_name='employed',
            name='Company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employed',
            name='Company_contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employed',
            name='Company_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employed',
            name='Company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employed',
            name='Company_zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employed',
            name='Income',
            field=models.CharField(choices=[('10,000-25,000', '10,000-25,000'), ('30,000-40,000', '30,000-40,000'), ('50,000-70,000', '50,000-70,000'), ('More than the choices', 'More than the choices')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employed',
            name='Position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employed',
            name='Years_of_experience',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
