# Generated by Django 3.2.5 on 2022-03-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0058_auto_20220322_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employed',
            old_name='Years_of_experience',
            new_name='Year_started',
        ),
    ]
