# Generated by Django 4.0.2 on 2022-03-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0055_alter_alumni_id_alter_contact_id_alter_employed_id_and_more'),
        ('CITAT', '0063_auto_20220325_1134'),
    ]

    operations = [
    ]
