# Generated by Django 3.2.5 on 2022-03-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0068_auto_20220329_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='Country',
            new_name='Country_alumni',
        ),
    ]
