# Generated by Django 3.2.5 on 2022-03-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0070_rename_country_alumni_alumni_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Year_graduated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='additional_degree',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
