# Generated by Django 3.1.7 on 2022-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0073_auto_20220331_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
    ]
