# Generated by Django 4.0.2 on 2022-03-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0072_auto_20220331_1254'),
        ('CITAT', '0074_auto_20220331_2001'),
    ]

    operations = [
    ]
