# Generated by Django 3.1.7 on 2022-04-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0076_alter_alumni_id_alter_contact_id_alter_employed_id_and_more'),
        ('CITAT', '0072_auto_20220331_1602'),
    ]

    operations = [
    ]
