# Generated by Django 3.1.7 on 2022-04-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0077_merge_20220405_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useremployed',
            name='alumni',
        ),
        migrations.DeleteModel(
            name='UserSelfemployed',
        ),
        migrations.DeleteModel(
            name='UserUnemployed',
        ),
        migrations.DeleteModel(
            name='UserEmployed',
        ),
    ]
