# Generated by Django 3.1.7 on 2022-04-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0078_auto_20220405_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_contact', models.CharField(max_length=200, null=True)),
                ('Company_email', models.CharField(max_length=200, null=True)),
                ('Position', models.CharField(max_length=200, null=True)),
                ('Year_started', models.CharField(max_length=200, null=True)),
                ('Company_pic', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CITAT.category')),
            ],
        ),
    ]
