# Generated by Django 4.0.2 on 2022-04-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0073_carausel'),
        ('CITAT', '0082_auto_20220406_1404'),
    ]

    operations = [
    ]
