# Generated by Django 3.2.5 on 2022-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0084_auto_20220410_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_email',
        ),
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(blank=True, default='ccs.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
