# Generated by Django 3.2.5 on 2022-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0085_auto_20220410_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_Telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_pic',
            field=models.ImageField(blank=True, default='ccs.jpg', null=True, upload_to=''),
        ),
    ]
