# Generated by Django 3.2.5 on 2022-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0086_auto_20220410_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
