# Generated by Django 3.2.5 on 2022-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0088_alter_jobs_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
