# Generated by Django 3.2.5 on 2022-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITAT', '0090_auto_20220411_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
